
[project]
name = "antfyutils"
requires-python = ">= 3.8"
license = {text = "GPLv3"}
version = "0.0.3"
dependencies = [
"aiohttp",
"dataclasses-json",
"toml_dataclass"
]
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"